global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: 'matching-engine-prod'
    env: 'production'

scrape_configs:
  - job_name: 'matching-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['matching-engine-service:8081']
        labels:
          application: 'matching-engine'
    
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-service:9092']
        labels:
          application: 'kafka'
    
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:9249']
        labels:
          application: 'flink'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert_rules.yml'
